
service: sample-aws-starter-project

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: sample/path/hello
          method: get
          cors: true

plugins:
  - serverless-offline
