
service: sample-aws-starter-project

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  # apiGateway: # Uncomment these two lines to enforce API Key Usage
    # apiKeySourceType: HEADER

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: sample/path/hello
          method: get
          cors: true
          # private: true # Uncomment this line to enforce API Key Usage

plugins:
  - serverless-offline
